# ====================================
#    APPLICATION CONFIG
# ====================================
spring.application.name=inventory-service
server.port=8082

# ====================================
#    DATABASE CONFIG
# ====================================
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_service
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.locations=classpath:db/migration

# ------------------------
# Kafka
# ------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.properties.specific.avro.reader=true

spring.kafka.properties.auto.register.schemas=true
spring.kafka.properties.use.latest.version=true

spring.kafka.properties.schema.registry.url=http://schema-registry:8081

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true
# ====================================
#    LOGGING CONFIGURATION
# ====================================
logging.level.root=info
logging.level.com.akul.microservices=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
#logging.pattern.console={"time":"%d{yyyy-MM-dd HH:mm:ss}","level":"%level","thread":"%thread","logger":"%logger","service":"${spring.application.name}","message":"%msg"}%n

# ====================================
#    ACTUATOR / PROMETHEUS / TRACING
# ====================================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# ====================================
#    EUREKA DISCOVERY
# ====================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# ====================================
inventory.reservation.minutes=10
inventory.ttl.check.millis=60000
