spring.application.name=inventory-service

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_service
spring.datasource.username=inventory_client
spring.datasource.password=a123123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

server.port=8082

# ------------------------
# Eureka
# ------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ------------------------
# Kafka
# ------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.properties.specific.avro.reader=true

spring.kafka.properties.auto.register.schemas=false
spring.kafka.properties.use.latest.version=true

spring.kafka.properties.schema.registry.url=http://localhost:8085

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true