version: "3.9"

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql_inventory
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_MYSQL_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: inventory_service
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${ROOT_MYSQL_PASS} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  inventory-service:
    image: andr72/inventory-service:dev-latest
    container_name: inventory-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_service?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASS}
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
  my-network:
    external: true